"""
The following codes are generated by AI. The members are solely responsible for any
errors made by said technology
"""

# clinic_appointment_system.py

# clinic_appointment_system.py

import csv
import heapq
from collections import defaultdict

# Data structures
appointments = []  # Priority queue
appointments_by_date = defaultdict(int)  # Count of appointments per day
patient_records = {}  # Hash table for patients

CSV_FILE = "appointments.csv"

# Load appointments from CSV
def load_appointments():
    try:
        with open(CSV_FILE, mode='r') as file:
            reader = csv.DictReader(file)
            for row in reader:
                urgency = int(row['urgency'])
                patient_id = row['patient_id']
                name = row['patient_name']
                date = row['date']
                heapq.heappush(appointments, (urgency, patient_id, name, date))
                appointments_by_date[date] += 1
                patient_records[patient_id] = (name, date, urgency)
    except FileNotFoundError:
        pass

# Save appointments to CSV
def save_appointments():
    with open(CSV_FILE, mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(['urgency', 'patient_id', 'patient_name', 'date'])
        for urgency, patient_id, name, date in appointments:
            writer.writerow([urgency, patient_id, name, date])

# Display help

def show_help():
    print("""
    How to use HospiCheck:
    - You can book, reschedule, or cancel appointments.
    - Choose 'Emergency' (0) or 'Routine' (1) for urgency.
    - Max of 5 appointments allowed per day.
    """)
    goBack = input("Enter 1 to exit: ")
    if goBack == '1':
        return main()


# Display appointment list

def display_appointments():
    if not appointments:
        print("There are no appointments. Would you like to add? Enter 1 for yes, 0 for no")
        return input("Choice: ") == '1'
    print("\nCurrent Appointments:")
    for urgency, patient_id, name, date in appointments:
        print(f"{name} (ID: {patient_id}) - Date: {date}, Urgency: {'Emergency' if urgency == 0 else 'Routine'}")
    return handle_existing_appointments()

# Handle existing appointments menu

def handle_existing_appointments():
    print("\nWould you like to reschedule, add more, or cancel an appointment?")
    print("Enter 0 to Reschedule")
    print("Enter 1 to Add another")
    print("Enter 2 to Cancel")
    print("Enter 3 to return to main menu")
    choice = input("Choice: ")
    if choice == '0':
        reschedule_appointment()
    elif choice == '1':
        book_appointment()
    elif choice == '2':
        cancel_appointment()
    return False

# Book appointment

def book_appointment():
    patient_id = input("Enter Patient ID: ")
    name = input("Enter Patient Name: ")
    urgency = int(input("Enter Urgency (0=Emergency, 1=Routine): "))

    # Suggest earliest available day for routine
    date = input("Enter Appointment Date: ")
    if urgency == 1:
        for offset in range(30):
            proposed_date = date  # Replace with proper date arithmetic if desired
            if appointments_by_date[proposed_date] < 5:
                date = proposed_date
                break

    if appointments_by_date[date] >= 5:
        print("Date full. Cannot book.")
        return

    heapq.heappush(appointments, (urgency, patient_id, name, date))
    appointments_by_date[date] += 1
    patient_records[patient_id] = (name, date, urgency)
    save_appointments()
    print("Appointment booked.")

# Reschedule appointment

def reschedule_appointment():
    patient_id = input("Enter Patient ID to reschedule: ")
    if patient_id not in patient_records:
        print("Patient not found.")
        return
    old_data = patient_records[patient_id]
    appointments[:] = [appt for appt in appointments if appt[1] != patient_id]
    heapq.heapify(appointments)
    appointments_by_date[old_data[1]] -= 1
    book_appointment()

# Cancel appointment

def cancel_appointment():
    patient_id = input("Enter Patient ID to cancel: ")
    if patient_id not in patient_records:
        print("Patient not found.")
        return
    date = patient_records[patient_id][1]
    appointments[:] = [appt for appt in appointments if appt[1] != patient_id]
    heapq.heapify(appointments)
    del patient_records[patient_id]
    appointments_by_date[date] -= 1
    save_appointments()
    print("Appointment canceled.")

# Main loop

def main():
    load_appointments()
    while True:
        print("""
        Welcome to HospiCheck! Your trusted clinic appointment application made by IDLE Checkers
        Enter 0 for Help
        Enter 1 for Current Appointment List
        Enter 2 to Exit
        """)
        choice = input("Choice: ")
        if choice == '0':
            show_help()
        elif choice == '1':
            if display_appointments():
                book_appointment()
        elif choice == '2':
            print("""
            Thank you for using HospiCheck. HospiCheck is made by IDLE Checkers and the following names are the members:
            Navor, Raiven Christian
            Nera, Christian Jacob
            Ordoño, Jims Harold
            """)
            break
        else:
            print("Invalid input. Try again.")

if __name__ == '__main__':
    main()

